### ISSUE TITLE
Not able to read characteristic from Wave Plus

### ISSUE THREAD

**Issue by henrikost** [Drolla/WavePlus_Bridge#20]
I am trying to access my new Wave Plus device over BLE from a Raspberry Pi using the waveplus_bridge_py application.

I am able to scan and find the device over BLE, but the application fails when reading the sensor data characteristic.
The waveplus.py attempt to read the characteristic UUID b42e2a68-.., but it fails.
And accessing the device using the nRF app from a phone shows that the device does not have such a UUID. It have some other (eg b42ebc9e-..), but they do not advertise with the READ property.

The device is also setup to use WiFi - and correctly sending data to your servers and my Airthings app.

**Comment by Drolla** [comment]
Hello,
I have just rejected my Wave Plus devices with the nRF app, and I could not see a b42ebc9e characteristics. [This page](https://ztroop.github.io/wave-reader-utils/specs/) does not know this characteristic. Moreover, b42ebc9e seems to be a fully unknown character chain on the internet.

You say "the device is also setup to use WiFi". Are you speaking about the Wave Plus device? This one has no WiFi interface. Or are you trying to connect View Plus that supports WiFi?

The Wave Plus Bridge is only supporting Wave Plus devices and no other devices from Airthings.

**Comment by henrikost** [comment]
Hi,

The characteristic has a longer UUID - this part is just the start, which differs from the official Wave Plus UUIDs.

But it turned out it is because I do not have a Wave Plus, but a View Plus. They have different characteristics, and it is not possible to read out the sensor data over BLE - only using WiFi and the Airthings Cloud..
